spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/recipes_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/recipes
          jwk-set-uri: http://keycloak:8090/realms/recipes/protocol/openid-connect/certs
springdoc:
  api-docs:
    enabled: true